### ISSUE TITLE
Remove the paths with greyscale images (again)

### ISSUE THREAD

**Issue by mfranzs** [MIT-6819-team/TF_colorization#17]

**Comment by mfranzs** [comment]
- [ ] #15 Make the all paths file first

**Comment by kocabey** [comment]
Code to eliminate grayscale images is taking some time. As of now, it's been running for 10 hours and has cleaned only 50% of the data.

**Comment by Winter-Guerra** [comment]
@kocabey yeah, the code takes a long time to run. I am working on an alternate version that doesn't use external calls to ImageMagic and therefore should be faster. It would also be nice if the script actually added the saturation data to the allpaths JSON file so that our data loader could comb out images below X% saturation at training time. This would allow us to tune how much of the training data we should ignore because it's not saturated.

**Comment by mfranzs** [comment]
@Winter-Guerra Have you considered using http://scikit-image.org/docs/dev/api/skimage.color.html#skimage.color.rgb2hsv ?

**Comment by Winter-Guerra** [comment]
@mfranzs Yes! That's what the new code uses. I'll push the file later today. I'm currently working on the JSON encoding bit so that I only have to run this code once.

**Comment by Winter-Guerra** [comment]
Because classifying 1.x million photos takes forever....

**Comment by kocabey** [comment]
@Winter-Guerra For now, I am following the paper and remove an image if no pixel had a value of ab above 5.
